-- CREATE TABLE MENU
CREATE TABLE
  IF NOT EXISTS "public"."menu" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(100) NOT NULL,
    "description" TEXT,
    "price" numeric(10, 2) DEFAULT 0.00 NOT NULL,
    "image_url" TEXT
  );

-- ENABLE RLS
ALTER TABLE "public"."menu" ENABLE ROW LEVEL SECURITY;

-- READ POLICY
CREATE POLICY "menu:authenticated:read" ON "public"."menu" FOR
SELECT
  TO "authenticated" USING (true);