-- CREATE TABLE
CREATE TABLE
  IF NOT EXISTS "public"."item_customization" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(100) NOT NULL,
    "additional_price" numeric(10, 2) DEFAULT 0.00 NOT NULL,
    "menu_item_id" integer NOT NULL
  );

-- ENABLE RLS
ALTER TABLE "public"."item_customization" ENABLE ROW LEVEL SECURITY;

-- READ POLICY
CREATE POLICY "item_customization:authenticated:read" ON "public"."item_customization" FOR
SELECT
  TO "authenticated" USING (true);