[build]
  command = "yarn build"
  functions = "src"
  publish = "dist"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/src/index/:splat"
  status = 200
  force = true

[dev]
  command = "yarn dev"
  port = 3000
  publish = "dist"
  targetPort = 8888
  framework = "#custom"
  autoLaunch = true